apiVersion: apps/v1
kind: Deployment
metadata:
  name: taximanagement
  labels:
    app: taximanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taximanagement
  template:
    metadata:
      labels:
        app: taximanagement
    spec:
      containers:
        - name: taximanagement
          image: username/taximanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5